# General Jekyll Config
url: https://github.com/gianjohansen
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
permalink:     /:title

# blog details
title: 'Journal - Gian Johansen | Web Developer'
tagline: 'I&#39;m Gian, a front-end web developer. I help turn brands into digital experiences because every brand has a story to tell. I&#39;m currently lead front-end engineer at OpenAgent.'
sidebar_image: /images/sidebar-cover.jpg

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#ED4035'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: gianjohansen
    #bitbucket: philipj
    #hacker_news: swanson
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: gianjohansen
    facebook: gian.johansen
    #tumblr: animalygifs
    linkedin: gianjohansen
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Gian Johansen
  email: gianjohansen@gmail.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-38281823-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
